### ISSUE TITLE
Save Mask Image to Image format (like png, jpg or any other image format) Using opencv

### ISSUE THREAD

**Issue by NaeemKhan333** [virafpatrawala/COCO-Semantic-Segmentation#1]
@virafpatrawala thanks for nice, Can you guide me how I can save the image to desk to generate png mask images. Thanks

**Comment by virafpatrawala** [comment]
You can download the COCO images from [here](http://cocodataset.org/#download).

To save using opencv check this: [cv2.imwrite](https://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#imwrite)

**Comment by NaeemKhan333** [comment]
I have download the images,annotation and get the mask using your notebook , but when I try to save the mask to storage device using the above function "cv2.imwrite("1.png",image)" , It does not save the mask, actually it save a black image without any mask.Can you help me out .Thanks

**Comment by virafpatrawala** [comment]
The mask has pixel values like 0, 1, 2... which are very small (given a range of 255) which is why on saving, it probably looks like a black image to the naked eye. However, if you again read this saved image using cv2.imread('1.png') and display it using the cv2 'imshow()' function, you should be able to see the mask properly.

Basically, the mask is being saved properly, you just can't see the small pixel values. Another option is to scale the pixel values to 255 before saving.

**Comment by NaeemKhan333** [comment]
But when we save it using matplotlib function savefig,it save the mask perfectly but it dimension get reduced.But I have see many mask which are visible by naked eye but in your case it is not visible.

**Comment by NaeemKhan333** [comment]
@virafpatrawala I have saved the mask as you said and read the mask using imread function , it does show proper yellowish mask on the image. Can you give me the reason why I am not getting yellowish mask. While I have re-scale the values and it is giving me the white color mask with black background.I want to get the yellow mask

**Comment by virafpatrawala** [comment]
How does the color of the mask matter? What matters for training a model is the pixel values, which you can scale/rescale back as you please. The colors are only shown by cv2 or matplotlib for visualization purposes. Depending on your use case keep scaling back and forth.

And if saving a "yellow" mask to local is so important, convert the mask to a 3 channel RGB image and change the pixel values to yellow in RGB.

**Comment by NaeemKhan333** [comment]
@virafpatrawala Thanks , I understand :+1:
