### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by MiguelAngeloMartinsRibeiro** [virafpatrawala/COCO-Semantic-Segmentation#2]
@virafpatrawala Hi, first of all thanks for your article. I think your code is all I need to finish my project. I need to transform a json file with a lot of annotations for different images into segmentation masks png's, and also I thin I'm going to use your data augmentation part too. 

I'm not using coco images but my own dataset with coco annotations and I got this error

<img width="1112" alt="Captura de ecrã 2021-08-08, às 20 56 11" src="https://user-images.githubusercontent.com/56026320/128644182-0355c1b6-5e0d-4c48-8d88-1da49244b85f.png">

My dataset have images of 550x550 pixels but I got the same error when I inserted that number in the input_image_size

Thank you for your time

Miguel

**Comment by virafpatrawala** [comment]
@MiguelAngeloMartinsRibeiro 
I'm sorry but it's difficult to debug without knowing more about your dataset and code, but there seems to be an extra dimension of '4' in your train_img variable. 

'img' is an array of size (batch_size, 224, 224, 3), so train_img needs to be of shape (224,224,3).
I'd recommend printing out the shape of all the important variables, and try to backtrack and find out the reason for the issue.

**Comment by MiguelAngeloMartinsRibeiro** [comment]
Maybe that's the problem cause when I run just "img" I get:

{'id': 174,
 'file_name': 'Image21945.png',
 'width': 550,
 'height': 550,
 'date_captured': '2021-07-18 22:14:26.478491',
 'license': 1,
 'coco_url': '',
 'flickr_url': ''}

and when I run mask I get a array
and when I run mask.shape I get (550,550)

img.shape gives me an error

**Comment by MiguelAngeloMartinsRibeiro** [comment]
@virafpatrawala  my problem is only in visualizeGenerator

**Comment by MiguelAngeloMartinsRibeiro** [comment]
@virafpatrawala so the problem is that img should be a (4,224,224,3) and it's this 

{'id': 174,
'file_name': 'Image21945.png',
'width': 550,
'height': 550,
'date_captured': '2021-07-18 22:14:26.478491',
'license': 1,
'coco_url': '',
'flickr_url': ''}

but the rest of the code worked fine

**Comment by MiguelAngeloMartinsRibeiro** [comment]
@virafpatrawala I just printed the shape of I in the first part and it's (550,550,4) maybe its because my images are RGBA

**Comment by MiguelAngeloMartinsRibeiro** [comment]
That was the problem ;) Solved it

**Comment by virafpatrawala** [comment]
@MiguelAngeloMartinsRibeiro Great! All the best with your project!
